import { AuthProvider } from "@/context/userDetail";
import { CountryProvider } from "@/context/contryDetails";
import { AddressProvider } from "@/context/address";
import { CartItemProvider } from "@/context/cartItems";
import './globals.css'
import { Work_Sans } from 'next/font/google';
import { getUserDetails } from '../lib/auth';
import { getTokenCookie , getCountryCookie} from '../lib/auth-cookies';
import { cookies } from 'next/headers';
import { CountryListProvider } from "@/context/countryList";
import Script from 'next/script'
// import { Work_Sans } from 'next/font/google';

const workSans = Work_Sans({ weight: ['400','500','600', '700'],
style: ['normal', 'italic'],
subsets: ['latin'],})


export const metadata = {
  title: 'Kuwa',
  description: 'Generated by create next app',
  title: 'GetKuwa: Supplements, Health &amp; Nutrition in UAE',
  description: 'GetKuwa helps you buy the best quality health supplements to boost your nutrition and fitness in UAE. Shop now and enjoy the benefits!',
}


const getUser = async () => {
  const nextCookies = cookies(); 
  const token = nextCookies.get('token');
  const user = nextCookies.get('userId');
  console.log("tokentoken",token)
  if((token && token.value) || (user && user.value)  ){
    try {
      const userLoginResp  =  await fetch(`${process.env.BACKEND_END_POINT_URL}/api/v1/customer/${user.value}`, {
        method: 'GET',
        headers: {
          'Content-Type': 'application/json',
          Authorization: 'Bearer ' + token.value,
        }
      })
      const userData = await userLoginResp.json();
      if(token && token.value){
        return {isLogin:true, userData:userData};
      }else{
        return {isLogin:false, userData:userData};
      }
     } catch (err) {
      return {isLogin:false,userData:null}
     }
  }else{
    return {isLogin:false,userData:null}
  }

};

const getCountryList = async() => {
  const getCountryListResp  =  await fetch(`${process.env.BACKEND_END_POINT_URL}/api/v1/active/countries/`, {
    method: 'GET',
    next: { revalidate: 300 } ,
    headers: {
      'Content-Type': 'application/json',
    },
  })
  const countryListData = await getCountryListResp.json();
  if(countryListData && countryListData.length > 0){
      return countryListData;
  }
}

export default async function RootLayout({ children }) {
  const userData = await getUser();
  const countryList = await getCountryList();
  const { isLogin= false, } = userData || {}
  let selectedCountryData = {};
  if(isLogin){
    const filteredCountry = countryList.find((data,index)=>data.id == userData.userData.country)
    selectedCountryData = filteredCountry;
  }else{
    const countryIdFromCookie = getCountryCookie();
    if(countryIdFromCookie){
      const filteredCountry = countryList.find((data,index)=>data.id == countryIdFromCookie)
      selectedCountryData = filteredCountry;
    }
  }





  return (
    <html lang="en">
      <link rel="shortcut icon" href="https://production-website-builds.s3.ap-south-1.amazonaws.com/kuwa/Kuwa-Favicon-32x32_32x32.png" type="image/png"></link>
      <body className={workSans.className}>
      <script type="text/javascript" src="https://cdn.checkout.com/js/framesv2.min.js" async></script>
      <script type="text/javascript" src="https://checkout.tabby.ai/tabby-promo.js" async></script>
      <Script src="https://cdn.tamara.co/widget/product-widget.min.js" strategy="lazyOnload" />
      <Script src="/tamara-script.js" strategy="lazyOnload" />
      <CountryListProvider countryList={countryList}>
        <CountryProvider countryCode={"AE"} selectedCountryData={selectedCountryData} countryList={countryList}>
          <AuthProvider authData={userData}>
            <CartItemProvider>
            <AddressProvider >
            {children}
            </AddressProvider> 
            </CartItemProvider>       
          </AuthProvider>
        </CountryProvider>
      </CountryListProvider>
      </body>
    </html>
  )
}
