import { AuthProvider } from "@/context/userDetail";
// import { CountryProvider } from "@/context/contryDetails";

import './globals.css'
import { Work_Sans } from 'next/font/google';
import { getUserDetails } from '../lib/auth';
import { getTokenCookie } from '../lib/auth-cookies';
import { cookies } from 'next/headers';
// import { Work_Sans } from 'next/font/google';

const workSans = Work_Sans({ weight: ['400', '700'],
style: ['normal', 'italic'],
subsets: ['latin'],})


export const metadata = {
  title: 'Kuwa',
  description: 'Generated by create next app',
}


const getUser = async () => {
  const nextCookies = cookies(); 
  const token = nextCookies.get('token');
  if(token){
    try {
      const userLoginResp  =  await fetch('https://api.kuwa.bevaleo.dev/api/v1/private/customer/1', {
        method: 'GET',
        headers: {
          'Content-Type': 'application/json',
          Authorization: 'Bearer ' + token.value,
        }
      })
      // const userData = await userLoginResp.json()
      const userData = {
        id:1,
        countryId: 1,
        countryCode: 'AE'
      }
      return userData;
     } catch (err) {
         return null
     }
  }else{
    return null
  }

};


export default async function RootLayout({ children }) {
  // const userData = await getUser();

  // const countryCode = userData && userData.countryCode || null

   

  // console.log("userData",userData)

  return (
    <html lang="en">
      <body className={workSans.className}>
     
      <script src="https://raw.githubusercontent.com/biggora/device-uuid/master/lib/device-uuid.min.js"></script>
        {/* <CountryProvider countryCode={"AE"}> */}
          {/* <AuthProvider  userData={userData}> */}
            {children}
          {/* </AuthProvider> */}
        {/* </CountryProvider> */}
      </body>
    </html>
  )
}
